travis:
  secure:
    BINSTAR_TOKEN: DoPGAKQakt9GYpjfv1e5hLghu6uufLFX4tuXMuq0IjXqUBm7LgEVOsHx+RcrUoMSOTFCQ4iKdS9iUU3M183ARhl16VdxMnR74urhi6KwTXwQ4T1x/rR08VCno3ztQUh/4m6HGEAWFWD1jEj1brY1HfOeSGOBZShO6XH1uflqPgV3uowWc0kJ/jUBO+008735PzIV/kcNGDzUMKp3uyJmkKNPJFpZO0CWN1b57Ovr65ZuWgWiYpIqzP2ACnAD/RW2J/5zAq7SFyQRa1GtuyUf9lQhPa9XPiajAIl0aMUObWKQT1jWAvCL88iD3e3WC4hiBf5CxiRGh7b1FSTi4jqpfoNIzG4b7AGa+yy02Z6l57AkfGq9+6ZmFpfMajRc9EhhQA5RXnBeOqYChKxjSuXYOAphuTSrFFiMIHQfZClO2Zco4Xh1ACNoQ9/01u/pewAfGNv7uj+0caVrcRGnQF24+9MeNL/aBkfI7YN/ctegaFphCts8iy81HYTvDyxtdkQCENxvkvP/nNMBt8Y6PwmpOZ2jHRdzwAR8jCw2xrcUdTquW6PMw2AXoCnH7qMUwFkIPkrRQgQ4v9Wqf0l+0fQf+i5CTIHNNc7WQuCqffZjixS3L/Hf4jAKhq3j/gGdpCQDXnWmtnsj6GmRQYkagglZPKmGcpklycuSdKlkqXjFETU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
