travis:
  secure:
    BINSTAR_TOKEN: kHzAO77vN9GxAyH1xE2RkpIpFbwuUMglIzg0U63nLX2qtZR3XTOX0NELh0rX5ZTq1Tz3WnQOj/thG+Nanlf0c0oxtE9TjpNqFiPsfzD55KEkUdHzPRuTlVoeJA7cYHFf7iPqTN2WMwfmU8Bmk1tgT6OLvZ2Th7Sq41jdScUzo17V2cpKXVBq/qivPdNw71qb7VxdqU5I51S0CitCiKUTWtAix+C02CCxp3uNXtj36HM8ti5xmQZUXsDZfcxMiNTf2DbhAyKk1stjODjLvLGXi1uqdcr7+cE9cs7WTQIIcwDQ4+BdFyQqp55oRZ9k6xEMELNGCv2XQLxfhxwUHhf5iNZaJXtFsxI+7lImGbz5yVhs+oSvumUNiUDfKFOtqcXibp4M8/83c1TamYMsDwGeJjdpbCxIu9GjiXtkpwJIDMd1Tg7Y0r8WRrTavKXCVxHTNmr4NbHdzTlxOJZSDaC5k629mbBtK+/C6gOfuE+/l7omzEU0FEaGGTInlb/GgSPU16rS+03ezWAg94r0EjtAGp+XHhAYHXvPo+I6GXmwXuNtnbu0ghmxKt4bHoD53RcYpzcVxjvjrzZ8jwF0PNoCF4ssX4jVcRoBhq+XDYN+2pWjx+v0lqXJW30yAupVBcpVNDX/Wh4jeA7nE0YaFkDw9fUH6HB7j+/sf3/zwWAT2H4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
